DROP TABLE IF EXISTS S;
DROP TABLE IF EXISTS T;

CREATE TABLE "S" (	
  V INTEGER,
  W INTEGER,
  X INTEGER,
  Y INTEGER,
  Z INTEGER );

CREATE TABLE "T" (	
  F INTEGER,
  G INTEGER,
  H INTEGER,
  I INTEGER,
  J INTEGER );
  
DROP TABLE IF EXISTS A;
DROP TABLE IF EXISTS B;
DROP TABLE IF EXISTS C;
DROP TABLE IF EXISTS D;

CREATE TABLE "A" (
  X INTEGER,
  Y INTEGER,
  Z INTEGER );
  
CREATE TABLE "B" (	
  W INTEGER,
  X INTEGER,
  Y INTEGER );
  
CREATE TABLE "C" (	
  V INTEGER,
  W INTEGER,
  X INTEGER );
  
CREATE TABLE "D" (	
  V INTEGER,
  X INTEGER,
  Z INTEGER );

INSERT INTO A(X,Y,Z) VALUES (3, 4, 5);
INSERT INTO B(W,X,Y) VALUES (2, 3, 4);
INSERT INTO C(V,W,X) VALUES (1, 2, 3);
INSERT INTO D(V,X,Z) VALUES (1, 3, 5);

INSERT INTO A(X,Y,Z) VALUES (42, 37, 37);
INSERT INTO A(X,Y,Z) VALUES (42, 73, 73);
INSERT INTO C(V,W,X) VALUES (37, 37, 42);
INSERT INTO C(V,W,X) VALUES (73, 73, 42);

